Emprende/Controllers/PersonaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Emprende.Extensions;
using Microsoft.Practices.EnterpriseLibrary.Logging;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using Emprende.Models;

namespace Emprende.Controllers
{
    public class PersonaController : Controller
    {
        // GET: Persona
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Dashboard()
        {

            int idUsuario = User.Identity.GetUserId<int>();
            string correo = User.Identity.GetUserName();

            if (idUsuario == 0) // no esta logeado
            {
                return RedirectToAction("Login", "Account");
            }
            else // esta loggeado
            {
                PersonasExtension persona = new PersonasExtension();
                MIS_Personas p = persona.consultarPersonaIdUsuario(idUsuario, correo);
                //p.datosCompletos = true; //todo quitar esto parche Fer
                ViewBag.persona = p;

                if (!ViewBag.persona.datosCompletos)
                {
                    return View("Editar");
                }
                else
                {
                    ViewBag.encabezado = "Bienvenido: " + ViewBag.persona.nombre + " " + ViewBag.persona.apellido;
                    return View();
                }
            }


        }
        public ActionResult Editar()
        {
            int idUsuario = User.Identity.GetUserId<int>();
            string correo = User.Identity.GetUserName();
            PersonasExtension persona = new PersonasExtension();
            MIS_Personas p = persona.consultarPersonaIdUsuario(idUsuario, correo);
            //p.datosCompletos = true; //todo quitar esto parche Fer
            ViewBag.persona = p;

            return View();
        }
        public JsonResult crearPersona(int idUsuario, string correo)
        {
            Resultado resultado;
            try
            {
                PersonasExtension persona = new PersonasExtension();
                persona.CrearPersona(idUsuario, correo);
                resultado = new Resultado(true, true);
            }
            catch (Exception e)
            {
                Logger.Write("Error en crear Persona" + e.Message);
                resultado = new Resultado(false, e.Message);
            }

            return Json(resultado);
        }
        public JsonResult consultarPersonaCompleta()
        {
            Resultado resultado;
            try
            {
                var context2 = new ApplicationDbContext();
                var user = context2.Users.Where(u => u.UserName == User.Identity.Name).First();

                PersonasExtension persona = new PersonasExtension();
                ViewBag.persona = persona.consultarPersonaIdUsuario(user.Id, user.Email);
                resultado = new Resultado(true, PersonasExtension.consultarPersonaCompleta(ViewBag.persona.id));
            }
            catch (Exception e)
            {
                Logger.Write("Error en crear Persona" + e.Message);
                resultado = new Resultado(false, e.Message);
            }

            return Json(resultado);
        }
        public JsonResult completarDatosGenerales
            (string cedula, string genero, string nombre1, string nombre2, string apellido1, string apellido2,
            string telefono, string celular, int nacionalidad, int estadoCivil, MIS_Direcciones direccion, int idTipoDocumento, DateTime fechaNacimiento, int idNivelEducacion,
            string nombre1Conyuge, string nombre2Conyuge, string apellido1Conyuge, string apellido2Conyuge, int idNacionalidadConyuge, DateTime fechaNacimientoConyuge, string documentoConyuge,
            int idConyuge
            )
        {
            Resultado resultado;
            try
            {
                var context2 = new ApplicationDbContext();
                var user = context2.Users.Where(u => u.UserName == User.Identity.Name).First();

                PersonasExtension persona = new PersonasExtension();
                ViewBag.persona = persona.consultarPersonaIdUsuario(user.Id, user.Email);
                PersonasExtension.completarDatosGenerales(ViewBag.persona.id, cedula, genero, nombre1, nombre2, apellido1, apellido2, telefono, celular, nacionalidad, estadoCivil, direccion, idTipoDocumento, fechaNacimiento, idNivelEducacion, nombre1Conyuge, nombre2Conyuge, apellido1Conyuge, apellido2Conyuge, idNacionalidadConyuge, fechaNacimientoConyuge, documentoConyuge, idConyuge);

                resultado = new Resultado(true, true);
            }
            catch (Exception e)
            {
                Logger.Write("Error en crear Persona" + e.Message);
                resultado = new Resultado(false, e.Message);
            }

            return Json(resultado);
        }

        public JsonResult consultarDireccionPersona()
        {
            Resultado resultado;
            try
            {
                var context2 = new ApplicationDbContext();
                var user = context2.Users.Where(u => u.UserName == User.Identity.Name).First();

                PersonasExtension persona = new PersonasExtension();
                ViewBag.persona = persona.consultarPersonaIdUsuario(user.Id, user.Email);

                resultado = new Resultado(true, PersonasExtension.consultarDireccionPersona(ViewBag.persona.id));
            }
            catch (Exception e)
            {
                Logger.Write("Error en crear Persona" + e.Message);
                resultado = new Resultado(false, e.Message);
            }

            return Json(resultado);
        }
    }
}

Emprende/Views/Persona/Dashboard.cshtml
@using Emprende.Models
@model LoginViewModel
@{
    ViewBag.Title = "Dashboard";
    Layout = "~/Views/Shared/UsuarioLayout.cshtml";
}
@section css{

}
@section js{

    <script src="~/js/Usuario/Dashboard.js"></script>
    <script src="~/js/Emprendimiento/CrearEmprendimiento.js"></script>
}

<ol class="breadcrumb">
    <li class="breadcrumb-item">
        <a href="@Url.Action("Dashboard","Persona")"><h2>@ViewBag.encabezado</h2> </a>
    </li>
</ol>

<div style="display:none" id="crearEmprendimiento" class="text-center">

    <button id="btnLgCrearEmprendimiento" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#modalCrearEmprendimiento">
        <a class="fa fa-plus-circle espacioVertical"></a>
        Registra tu Empredimiento
        <br />
        Aquí !
    </button>

</div>

<div style="display:none" class="card mb-3 espacioVertical" id="misPostulaciones">
    <div class="card-header">
        <div class="row">
            <h3 class="col-sm-12"> Mis postulaciones</h3>
        </div>
    </div>

    <div class="card-body">
        <div class="row top-space">
            <div class="col-sm-12">
                <table id="tblMisPostulaciones" class="table table-bordered" width="100%"></table>
            </div>
        </div>
    </div>

    <div class="card-footer ">
        <div class="row ">
            <div class="col text-right">
                @*<button id="btnAgregarEmprendimiento" class=" btn btn-primary" data-toggle="modal" data-target="#modalRegistarEmprendimiento">Agregar emprendimiento</button>*@
            </div>

        </div>
    </div>

</div>

<div style="display:none" class="card mb-3 espacioVertical" id="misEmprendimientos">
    <div class="card-header">
        <div class="row">
            <h3 class="col-sm-12"> Mis emprendimientos</h3>
        </div>
    </div>

    <div class="card-body">
        <div class="row top-space">
            <div class="col-sm-12">
                <table id="tblMisEmprendimientos" class="table table-bordered" width="100%"></table>
            </div>
        </div>
    </div>

    <div class="card-footer ">
        <div class="row ">
            <div class="col text-right">
                <button id="btnAgregarEmprendimiento" class=" btn btn-primary" data-toggle="modal" data-target="#modalCrearEmprendimiento">Agregar emprendimiento</button>
            </div>

        </div>
    </div>

</div>


<!-- Modal  Crear Emprendimiento-->
<div class="modal fade" id="modalCrearEmprendimiento" role="dialog">
    <div class="modal-dialog">

        <!-- Modal content-->
        <div class="modal-content">
            <!-- Modal Header-->
            <div class="modal-header">
                <h4 class="modal-title text-left">Nuevo Emprendimiento</h4>
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>

            </div>
            <!-- Modal Body-->
            <div class="modal-body">
                <div class="row form-group">
                    <label class="col-sm-3"> Nombre: </label>
                    <input id="txtNombreEmprendimiento" class="col-sm-8 form-control" type="text" />
                </div>
            </div>
            <!-- Modal footer-->
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
                <button id="btnCrearEmprendimiento" type="button" class="btn btn-primary"><i class="fa fa-check-circle"></i> Crear </button>
            </div>
        </div>

    </div>
</div>

<!-- Modal Convocatorias abiertas-->
<div class="modal fade" id="modalPostular" role="dialog">
    <div class="modal-dialog">

        <!-- Modal content-->
        <div class="modal-content">
            <!-- Modal Header-->
            <div class="modal-header">
                <h4 class="modal-title text-left">Convocatorias Abiertas</h4>
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>

            </div>
            <!-- Modal Body-->
            <div class="modal-body">
                <div class="row form-group conConvocatorias" style="display:none">
                    <input id="txtIdEmprendimiento" type="hidden" />
                    <label class="col-sm-3">Seleccione:</label>
                    <select id="slcConvocatoriasAbiertas" class="form-control col-sm-8"></select>
                </div>

                <div class="row form-group sinConvocatorias text-center" style="display:none">
                    <div class="col-sm-10 offset-sm-1">
                        No hay convocatorias abiertas actualmente. <br />
                        Te notificaremos cuando se abra la siguiente
                    </div>
                </div>

            </div>
            <!-- Modal footer-->
            <div class="modal-footer conConvocatorias" style="display:none">
                <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
                <button id="btnPostularAConvocatoria" type="button" class="btn btn-primary"><i class="fa fa-check-circle"></i> Postular </button>
            </div>
        </div>

    </div>
</div>