Emprende/Models/Emprendimientos.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emprende.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Emprendimientos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Emprendimientos()
        {
            this.CON_canvas = new HashSet<CON_canvas>();
            this.CON_postulaciones = new HashSet<CON_postulaciones>();
            this.Productos = new HashSet<Productos>();
            this.socios = new HashSet<socios>();
        }
    
        public int id { get; set; }
        public int idPersona { get; set; }
        public string nombre { get; set; }
        public string descripcion { get; set; }
        public Nullable<decimal> PrecioPromedioPonderado { get; set; }
        public Nullable<decimal> CostoPromedioPonderado { get; set; }
        public Nullable<int> idEstado { get; set; }
        public string ruc { get; set; }
        public Nullable<int> unidadesVentaActual { get; set; }
        public Nullable<int> unidadesVentaProy { get; set; }
        public Nullable<bool> completo { get; set; }
        public Nullable<int> mesesEquilibrio { get; set; }
        public Nullable<decimal> costosFijos { get; set; }
        public Nullable<bool> tieneProducto { get; set; }
        public Nullable<int> tieneVentas { get; set; }
        public Nullable<int> tiempoVentas { get; set; }
        public Nullable<int> idTipoLugar { get; set; }
        public Nullable<int> idDireccion { get; set; }
        public Nullable<int> NumEmpleados { get; set; }
        public Nullable<int> NumProveedores { get; set; }
        public Nullable<int> NumClientes { get; set; }
        public Nullable<int> NumConsumidores { get; set; }
        public Nullable<bool> estaConstituida { get; set; }
        public string brief { get; set; }
        public Nullable<int> idMediosInformacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CON_canvas> CON_canvas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CON_postulaciones> CON_postulaciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Productos> Productos { get; set; }
        public virtual MIS_Personas MIS_Personas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<socios> socios { get; set; }
        public virtual ItemsCatalogos ItemsCatalogos { get; set; }
        public virtual MIS_Direcciones MIS_Direcciones { get; set; }
    }
}

Emprende/Controllers/EmprendimientoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Emprende.Models;
using Emprende.Extensions;
using Microsoft.Practices.EnterpriseLibrary.Logging;
namespace Emprende.Controllers
{
    public class EmprendimientoController : Controller
    {
        // GET: Emprendimiento
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult CrearEmprendimiento()
        {
            return View();
        }
        public ActionResult EditarEmprendimiento()
        {
            int idEmprendimiento = Convert.ToInt32(Url.RequestContext.RouteData.Values["id"]);

            ViewBag.emprendimiento = EmprendimientoExtension.consultarEmprendimientoId(idEmprendimiento);

            return View();
        }
        public JsonResult guardarEmprendimiento(string nombre)
        {
            Resultado resultado;
            try
            {
                var context2 = new ApplicationDbContext();
                var user = context2.Users.Where(u => u.UserName == User.Identity.Name).First();


                PersonasExtension persona = new PersonasExtension();
                ViewBag.persona = persona.consultarPersonaIdUsuario(user.Id, user.Email);
                EmprendimientoExtension emprendimiento = new EmprendimientoExtension();
                resultado = new Resultado(true, emprendimiento.crearEmprendimiento(ViewBag.persona.id, nombre).id);
            }
            catch (Exception e)
            {
                Logger.Write("Error en crear Emprendmiento" + e.Message);
                resultado = new Resultado(false, e.Message);
            }

            return Json(resultado);
        }

        public JsonResult completarEmprendimiento(int idEmprendimiento, string descripcion, string ruc, Boolean tieneProducto, int? tieneVentas, int? tiempoVentas, MIS_Direcciones direccion, int bandera, bool estaConstituida, int idMedioInformacion)
        {
            Resultado resultado;
            try
            {
                resultado = new Resultado(true, EmprendimientoExtension.completarEmprendimiento(idEmprendimiento, descripcion, ruc, tieneProducto, tieneVentas, tiempoVentas??0, direccion, bandera, estaConstituida,idMedioInformacion));                
            }
            catch (Exception e)
            {
                Logger.Write("Error en crear Emprendmiento" + e.Message);
                resultado = new Resultado(false, e.Message);
            }

            return Json(resultado);
        }

        public JsonResult consultarEmprendimientosPorPersona()
        {
            Resultado resultado;
            try
            {
                var context2 = new ApplicationDbContext();
                var user = context2.Users.Where(u => u.UserName == User.Identity.Name).First();

                PersonasExtension persona = new PersonasExtension();
                ViewBag.persona = persona.consultarPersonaIdUsuario(user.Id, user.Email);

                List<Emprendimientos> emprendimientos = new List<Emprendimientos>();
                emprendimientos = EmprendimientoExtension.consultarEmprendimientosPorPersona(ViewBag.persona.id);
                if (emprendimientos.Count == 0)
                    resultado = new Resultado(true, 0);
                else
                    resultado = new Resultado(true, emprendimientos);
            }
            catch (Exception e)
            {
                Logger.Write("Error en consultar emprendimientos por persona" + e.Message);
                resultado = new Resultado(false, e.Message);
            }

            return Json(resultado);
        }
        public JsonResult consultarEmprendimientosCompletosPorPersona()
        {
            Resultado resultado;
            try
            {
                var context2 = new ApplicationDbContext();
                var user = context2.Users.Where(u => u.UserName == User.Identity.Name).First();

                PersonasExtension persona = new PersonasExtension();
                ViewBag.persona = persona.consultarPersonaIdUsuario(user.Id, user.Email);

                List<Emprendimientos> emprendimientos = new List<Emprendimientos>();
                emprendimientos = EmprendimientoExtension.consultarEmprendimientosCompletosPorPersona(ViewBag.persona.id);
                if (emprendimientos.Count == 0)
                    resultado = new Resultado(true, 0);
                else
                    resultado = new Resultado(true, emprendimientos);
            }
            catch (Exception e)
            {
                Logger.Write("Error en consultar emprendimientos por persona" + e.Message);
                resultado = new Resultado(false, e.Message);
            }

            return Json(resultado);
        }

        public JsonResult consultarEmprendimientoId(int idEmprendimiento)
        {
            Resultado resultado;
            try
            {
                resultado = new Resultado(true, EmprendimientoExtension.consultarEmprendimientoId(idEmprendimiento));
            }
            catch (Exception e)
            {
                Logger.Write("Error en consultar emprendimiento Completo" + e.Message);
                resultado = new Resultado(false, e.Message);
            }

            return Json(resultado);
        }
    }
}

Emprende/Views/Emprendimiento/CrearEmprendimiento.cshtml
@{
    //ViewBag.Title = "Crear Emprendimiento";
    Layout = "~/Views/Shared/UsuarioLayout.cshtml";
}

@section css{


}
@section js{

    <script src="~/js/Emprendimiento/CrearEmprendimiento.js"></script>
    <script src="~/js/SCO/scoring.js"></script>
}

<ol class="breadcrumb">
    <li class="breadcrumb-item">
        <a href="@Url.Action("CrearEmprendimiento","Emprendimiento")"><h2>Crear Emprendimiento</h2></a>
    </li>
</ol>

<div class="row">
    <div class="col-sm-10 offset-sm-1">
        <div class="card mb-3 espacioVertical">
            <div class="card-header">
                <div class="row">
                    <h3 class="col-sm-12"> Datos del emprendimiento </h3>
                </div>
            </div>

            <div class="card-body">
                <div class="row">
                    <label class="col-sm-3">No. ruc:</label>
                    <input id="txtRucEmprendimiento" class="col-sm-5 form-control" type="text" placeholder="Ejm: 179385001" />
                </div>
                <div class="row espacioVertical">
                    <label class="col-sm-3">Nombre:</label>
                    <input id="txtNombreEmprendimiento" class="col-sm-5 form-control" type="text" placeholder="Nombre" />
                </div>
                <div class="row espacioVertical">
                    <label class="col-sm-3">Descripcion:</label>
                    <textarea id="txtDescripcionEmprendimiento" class="col-sm-9 form-control" rows="4" placeholder="Descripcion"></textarea>
                </div>

            </div>

            <div class="card-footer ">
                <div class="row ">
                    @*<div class="col text-right">
                            <button id="btnGuardarEmprendimiento" class=" btn btn-primary">Guardar emprendimiento</button>
                        </div>*@

                </div>
            </div>

        </div>

        <div class="card mb-3 espacioVertical">
            <div class="card-header">
                <div class="row">
                    <h3 class="col-sm-12"> Socios  </h3>
                </div>
            </div>

            <div class="card-body">

                <div class="row ">
                    <div class="col text-left">
                        <button class="btn btn-primary" id="btnAgregarSocio" type="button" data-toggle="modal" data-target="#modalSocio"> <i class="fa fa-plus-circle"></i> Agregar Socio</button>
                    </div>
                </div>

                <table id="tblSocios" class="table table-bordered espacioVertical" width="100%">
                    <thead>
                        <tr>
                            <th>Nombre</th>
                            <th>Teléfono</th>
                            <th>Cargo</th>
                            <th>Aporte</th>
                            <th>Porcentaje %</th>
                        </tr>
                    </thead>
                </table>

            </div>

            @*<div class="card-footer ">
                    <div class="row ">
                        <div class="col text-right">
                            <button id="btnGuardarEmprendimiento" class=" btn btn-primary">Guardar</button>
                        </div>

                    </div>
                </div>*@

        </div>

        <div class="card mb-3 espacioVertical">
            <div class="card-header">
                <div class="row">
                    <h3 class="col-sm-12"> Cuestionario  </h3>
                </div>
            </div>

            <div class="card-body" id="dvQ">


            </div>

            <div class="card-footer ">
                <div class="row ">
                    <div class="col text-right">
                        <button id="btnGuardarEmprendimiento" class=" btn btn-primary">Guardar</button>
                    </div>

                </div>
            </div>

        </div>
    </div>
</div>


<!-- Modal Agregar socio-->
<div class="modal fade" id="modalSocio" role="dialog">
    <div class="modal-dialog">

        <!-- Modal content-->
        <div class="modal-content">
            <!-- Modal Header-->
            <div class="modal-header">
                <h4 class="modal-title text-left">Datos Socio</h4>
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>

            </div>
            <!-- Modal Body-->
            <div class="modal-body">

                <div class="row form-group">
                    <div class="col-md-7">
                        <input type="text" id="txtIdEmprendimiento" class="form-control" value="" />
                    </div>
                    <div class="col-md-7">
                        <input type="hidden" id="txtIdSocio" class="form-control" value="0" />
                    </div>
                </div>

                <div class="row form-group">
                    <label for="txtnombreSocio" class="col-md-3 col-md-offset-1 control-label">Nombre:</label>
                    <div class="col-md-7">
                        <input type="text"  id="txtnombreSocio" class="form-control" />
                    </div>
                </div>

                <div class="row form-group">
                    <label for="txtTelefonoSocio" class="col-md-3 col-md-offset-1 control-label">Teléfono:</label>
                    <div class="col-md-7">
                        <input type="text" id="txtTelefonoSocio" class="form-control" />
                    </div>

                </div>
                <div class="row form-group">
                    <label for="txtCargoSocio" class="col-md-3 col-md-offset-1 control-label">Cargo:</label>
                    <div class="col-md-7">
                        <input type="text" id="txtCargoSocio" class="form-control" />
                    </div>
                </div>

                <div class="row form-group">
                    <label for="txtAporteSocio" class="col-md-3 col-md-offset-1 control-label">Aporte:</label>
                    <div class="col-md-7">
                        <input type="text" id="txtAporteSocio" class="form-control" />
                    </div>

                </div>
                <div class="row form-group">
                    <label for="txtPorcentajeSocio" class="col-md-3 col-md-offset-1 control-label">Porcentaje %:</label>
                    <div class="col-md-7">
                        <input type="text" id="txtPorcentajeSocio" class="form-control" />
                    </div>
                </div>

            </div>
            <!-- Modal footer-->
            <div class="modal-footer">
                <button id="borrarSocio" type="button" class="btn btn-danger" data-dismiss="modal">Borrar Socio</button>
                <button id="btnGuardarSocio" type="button" class="btn btn-primary">Guardar</button>
            </div>
        </div>

    </div>
</div>