Cobranza/Controllers/ReportesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Cobranza.Controllers
{
    public class ReportesController : Controller
    {
        // GET: Reportes
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Cosechas()
        {
            return View();
        }
    }
}

Cobranza/Views/Reportes/Cosechas.cshtml
@{string urlEmprende = System.Configuration.ConfigurationManager.AppSettings["urlEmprende"];}
@{
    ViewBag.Title = "Cosechas";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section css{


}
@section js{
    <script src="@urlEmprende/vendor/dataTables/dataTables.buttons.min.js"></script>
    <script src="@urlEmprende/vendor/dataTables/jszip.min.js"></script>
    <script src="@urlEmprende/vendor/dataTables/buttons.html5.min.js "></script>
    <script src="~/js/ReporteCosechas.js"></script>

}

<ol class="breadcrumb">
    <li class="breadcrumb-item">
        <a href="@Url.Action("Cosechas","Reportes")"><h2> Reporte Cosechas </h2>  </a>
    </li>
</ol>

<div class="card mb-3 espacioVertical">

    <div class="card-header">
        <div class="row">
            <h4 class="col-md-12">Resumen </h4>
        </div>
    </div>

    <div class="card-body">
        <div class="row">
            <label class="col-sm-1 offset-sm-1">Desde:</label>
            <div class="col-sm-2">
                <input id="txtDesde" type="date" class="form-control" />
            </div>
            <label class="col-sm-1">Hasta:</label>
            <div class="col-sm-2">
                <input id="txtHasta" type="date" class="form-control" />
            </div>
            <div class="col-sm-3 offset-sm-1 text-center">
                <button id="btnConsultar" class="btn btn-primary btn-block">Consultar</button>
            </div>
        </div>
        
        <div class="row espacioVertical">

            <div class="col-sm-12">
                <table id="tblReporteCosechas" class="table table-bordered table-sm table-responsive" width="100%"></table>
            </div>
        </div>
    </div>

    @*<div class="card-footer">

            <div class="row">
                <label id="txtDescripcion" class="col-md-12">@ViewBag.descripcion</label>
            </div>

        </div>*@

</div>