Cobranza/Controllers/PagosController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using Cobranza.Extensions;
using Microsoft.Practices.EnterpriseLibrary.Logging;
using Cobranza.Models;

namespace Cobranza.Controllers
{
    public class PagosController : Controller
    {
        // GET: Pagos
        public ActionResult Index()
        {
            int idDeudor;
            ViewBag.id = Url.RequestContext.RouteData.Values["id"];
            idDeudor = Convert.ToInt32(ViewBag.id);
            DeudorExtension deudor = new DeudorExtension();
            ViewBag.nombreDeudor = deudor.consultarDeudor(idDeudor).nombre;

            return View();

        }

        public ActionResult Deudor()
        {
            int idTipo, idReferencia;
            COB_VW_deudores elDeudor;

            idTipo = Convert.ToInt32(Url.RequestContext.RouteData.Values["id"]);
            idReferencia = Convert.ToInt32(Url.RequestContext.RouteData.Values["id2"]);

            DeudorExtension deudor = new DeudorExtension();
            elDeudor = deudor.consultarDeudor(idTipo, idReferencia);
            
            ViewBag.id = elDeudor.id;                        
            ViewBag.nombreDeudor = elDeudor.nombre;

            return View("Index");

        }

        public ActionResult PagosTotales()
        {
            DateTime actual = DateTime.Now;
            DateTime inicioMes = new DateTime(actual.Year, actual.Month, 1);
            ViewBag.descripcion = "Período: " + inicioMes.Day.ToString() + " - " + actual.Day.ToString() + " de " + actual.ToString("MMMM");
            return View();

        }

        public ActionResult CargarPagos()
        {


            return View();

        }
        public JsonResult ingresarPago(int idDeudor, decimal valor, bool esConfirmado, int tipoPago, string documento)
        {
            Resultado resultado;
            try
            {
                PagosExtension pagosE = new PagosExtension();
                pagosE.ingresarPago(idDeudor, valor, esConfirmado, tipoPago, documento);

                resultado = new Resultado(true, true);
            }
            catch (Exception e)
            {
                Logger.Write("Error en ingresar pagos" + e.Message);
                resultado = new Resultado(false, e.Message);
            }
            return Json(resultado);
        }

        public JsonResult consultarPagosDeudor(int idDeudor)
        {
            Resultado resultado;
            try
            {
                PagosExtension pagosE = new PagosExtension();
                resultado = new Resultado(true, pagosE.consultarPagosDeudor(idDeudor));
            }
            catch (Exception e)
            {
                Logger.Write("Error en consultar pagos deudor" + e.Message);
                resultado = new Resultado(false, e.Message);
            }
            return Json(resultado);
        }
        public JsonResult consultarDeudor(int idDeudor)
        {
            Resultado resultado;
            try
            {
                DeudorExtension deudorE = new DeudorExtension();
                resultado = new Resultado(true, deudorE.consultarDeudor(idDeudor));
            }
            catch (Exception e)
            {
                Logger.Write("Error en consultar deudor" + e.Message);
                resultado = new Resultado(false, e.Message);
            }
            return Json(resultado);
        }

        public JsonResult consultarTodosPagos()
        {
            Resultado resultado;
            try
            {
                TodosPagosExtension todosPagos = new TodosPagosExtension();
                resultado = new Resultado(true, todosPagos.consultarTodosPagos());
            }
            catch (Exception e)
            {
                Logger.Write("Error en consultar Todos los pagos" + e.Message);
                resultado = new Resultado(false, e.Message);
            }
            return Json(resultado);
        }

        public JsonResult consultarTodosPagosParametros(DateTime desde, DateTime hasta)
        {
            Resultado resultado;
            try
            {
                TodosPagosExtension todosPagos = new TodosPagosExtension();
                resultado = new Resultado(true, todosPagos.consultarTodosPagos(desde, hasta));
            }
            catch (Exception e)
            {
                Logger.Write("Error en consultar Todos los pagos" + e.Message);
                resultado = new Resultado(false, e.Message);
            }
            return Json(resultado);
        }              

        //[HttpPost]
        public JsonResult uploadExcel()
        {
            Resultado resultado;
            string filePath = AppDomain.CurrentDomain.BaseDirectory + @"Upload\pagos.xlsx";

            //try
            //{
                PagosExtension pago = new PagosExtension();
                HttpPostedFile miArchivo;
                HttpContext context = System.Web.HttpContext.Current;
                System.Collections.Specialized.NameValueCollection form = context.Request.Form;

                if (context.Request.Files.Count > 0)
                {
                    miArchivo = context.Request.Files[0];

                    if ((miArchivo != null) && (miArchivo.ContentLength > 0) && !string.IsNullOrEmpty(miArchivo.FileName))
                    {

                        miArchivo.SaveAs(filePath);
                        pago.ingresarPagosFromFile(filePath);
                        resultado = new Resultado(true, "Pagos cargados con correctamente");
                    }
                    else
                    {
                        throw new System.ArgumentException("Error al cargar pagos", "error");
                    }
                }
                else
                {
                    throw new System.ArgumentException("Error al cargar pagos", "error");
                }
                
            //}
            //catch (Exception e)
            //{
                //Logger.Write("Error en Cargar pagos desde archivo" + e.Message);
                //resultado = new Resultado(false, e.Message);
            //}
            return Json(resultado);

        }

    }
}

Cobranza/Views/Pagos/CargarPagos.cshtml
@{string urlEmprende = System.Configuration.ConfigurationManager.AppSettings["urlEmprende"];}
@{
    ViewBag.Title = "Modulo de Cobranza";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section css{

    <link href="@urlEmprende/vendor/datatables/dataTables.bootstrap4.css" rel="stylesheet">

}
@section js{
    <script src="@urlEmprende/vendor/datatables/jquery.dataTables.js"></script>
    <script src="@urlEmprende/vendor/datatables/dataTables.bootstrap4.js"></script>
    <script src="~/js/CargarPagos.js?v=1.01"></script>

}

@*inicio titulo*@
<ol class="breadcrumb">
    <li class="breadcrumb-item">
        <a href="@Url.Action("CargarPagos","Pagos")"><h2> Cargar Pagos </h2>  </a>
    </li>
</ol>
<div class="row">
    <input type="file" id="uploadPagos" title="Seleccione un archivo" class="col-md-6" accept=".xls,.xlsx" />
    <button id="btnCargarPagos" class="btn btn-primary col-md-2"><i class="fa fa-save"></i> Cargar Pagos </button>
</div>
@*fin titulo*@

Cobranza/Views/Pagos/Index.cshtml
@{string urlEmprende = System.Configuration.ConfigurationManager.AppSettings["urlEmprende"];}
@{
    ViewBag.Title = "Modulo de Cobranza";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section css{

    <link href="@urlEmprende/vendor/datatables/dataTables.bootstrap4.css" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.1/css/bootstrap.css" rel="stylesheet">
    <link href="https://cdn.datatables.net/buttons/1.5.2/css/buttons.bootstrap4.min.css" rel="stylesheet">
}
@section js{
    <script src="@urlEmprende/vendor/datatables/jquery.dataTables.js"></script>
    <script src="@urlEmprende/vendor/datatables/dataTables.bootstrap4.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.5.2/js/dataTables.buttons.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.5.2/js/buttons.bootstrap4.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.36/pdfmake.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.36/vfs_fonts.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.5.2/js/buttons.html5.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.5.2/js/buttons.print.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.5.2/js/buttons.colVis.min.js"></script>

    <script src="~/js/Pagos.js?v=1.01"></script>
}



<div class="portlet-title">
    @*inicio titulo*@
    <ol class="breadcrumb">
        <li class="breadcrumb-item">
            <a href="@Url.Action("Index","Pagos")"><h2> @ViewBag.nombreDeudor</h2>  </a>
        </li>
    </ol>
    @*fin titulo*@

    <div class="clearfix"></div>

    <div class="row espacioVertical">
        <div class="col text-right">
            <button class="btn btn-primary" id="btnAgregarPago" type="button" data-toggle="modal" data-target="#modalAgregarPago"> <i class="fa fa-plus-circle"></i> Agregar Pago</button>
        </div>
    </div>

    <div class="clearfix"></div>

    <div class="card mb-3 espacioVertical">

        <div class="card-header">
            <div class="row">
                <h4 class="col-md-12">Deudas </h4>
            </div>
        </div>

        <div class="card-body">
            <div class="row">

                <div class="col-sm-12">
                    <table id="tblDeudas" class="table table-bordered" width="100%"></table>
                </div>
            </div>
        </div>

        @*<div class="card-footer">

                <div class="row">
                    <h4 class="col-md-12">Última actualización: mes en curso </h4>
                </div>

            </div>*@

    </div>

    <div class="card mb-3 ">

        <div class="card-header">
            <div class="row">
                <h4 class="col-md-12">Cuotas </h4>
            </div>
        </div>

        <div class="card-body">
            <div class="row">

                <div class="col-sm-12">
                    <table id="tblCuotas" class="table table-bordered" width="100%">
                        <thead>
                            <tr>
                                <th>#</th>
                                <th>Fecha</th>
                                <th>Capital</th>
                                <th>Aporte</th>
                                <th>Total</th>
                                <th>Estado</th>
                                <th>F. Pago</th>
                                <th>Pagado</th>
                                <th>Pagado Capital</th>
                                <th>Pagado Aporte</th>
                                <th>Saldo Capital</th>
                                <th>Saldo Aporte</th>
                            </tr>
                        </thead>
                        <tbody></tbody>
                    </table>

                </div>
            </div>
        </div>

        @*<div class="card-footer">

                <div class="row">
                    <h4 class="col-md-12">Ultima actualizacion: mes en curso </h4>
                </div>

            </div>*@

    </div>

    <div class="card mb-3">

        <div class="card-header">
            <div class="row">
                <h4 class="col-md-12">Pagos</h4>
            </div>
        </div>

        <div class="card-body">
            <div class="row">

                <div class="col-sm-12">
                    <table id="tblPagos" class="table table-bordered " width="100%">

                        <thead>
                            <tr>
                                <th>Fecha</th>
                                <th>Valor</th>
                                <th>Tipo</th>
                                <th>Documento</th>
                            </tr>
                        </thead>
                        <tbody></tbody>
                    </table>

                </div>
            </div>
        </div>

        @*<div class="card-footer">

                <div class="row">
                    <h4 class="col-md-12">Ultima actualizacion: mes en curso </h4>
                </div>

            </div>*@

    </div>



</div>



<!-- Modal Agregar Pago-->
<div class="modal fade" id="modalAgregarPago" role="dialog">
    <div class="modal-dialog">

        <!-- Modal content-->
        <div class="modal-content">
            <!-- Modal Header-->
            <div class="modal-header">
                <h4 class="modal-title text-left">Agregar Pago</h4>
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>

            </div>
            <!-- Modal Body-->
            <div class="modal-body">

                <div class="row form-group">
                    @*<label for="txtidDeudorAgregarPago" class="col-md-3 col-md-offset-1 control-label">Deudor:</label>*@
                    <div class="col-md-7">
                        <input type="hidden" id="txtidDeudorAgregarPago" class="form-control" value="@ViewBag.id" />
                    </div>
                </div>

                <div class="row form-group">
                    <label for="txtValorAgregarPago" class="col-md-3 col-md-offset-1 control-label">Valor:</label>
                    <div class="col-md-7">
                        <input type="text" id="txtValorAgregarPago" class="form-control" />
                    </div>
                </div>

                <div class="row form-group">
                    <label for="slcTipoPagoAgregarPago" class="col-md-3 col-md-offset-1 control-label">Tipo de pago:</label>
                    <div class="col-md-7">
                        <select id="slcTipoPagoAgregarPago">
                            <option value="">Seleccione</option>
                            <option value="1">Efectivo</option>
                            <option value="2">Transferencia</option>
                            <option value="3">Cheque</option>
                        </select>
                    </div>
                </div>

                <div class="row form-group">
                    <label for="txtDocumentoAgregarPago" class="col-md-3 col-md-offset-1 control-label">Documento:</label>
                    <div class="col-md-7">
                        <input type="text" id="txtDocumentoAgregarPago" class="form-control" />
                    </div>

                </div>

            </div>
            <!-- Modal footer-->
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
                <button id="btnGuardarPago" type="button" class="btn btn-default">Guardar</button>
            </div>
        </div>

    </div>
</div>

Cobranza/Views/Pagos/PagosTotales.cshtml
@{string urlEmprende = System.Configuration.ConfigurationManager.AppSettings["urlEmprende"];}
@{
    ViewBag.Title = "Pagos";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section css{

    @*<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/dt/dt-1.10.18/datatables.min.css" />*@
    <link href="@urlEmprende/vendor/datatables/dataTables.bootstrap4.css" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.1/css/bootstrap.css" rel="stylesheet">
    <link href="https://cdn.datatables.net/buttons/1.5.2/css/buttons.bootstrap4.min.css" rel="stylesheet">
}
@section js{
    @*<script type="text/javascript" src="https://cdn.datatables.net/v/dt/dt-1.10.18/datatables.min.js"></script>*@
    <script src="@urlEmprende/vendor/datatables/jquery.dataTables.js"></script>
    <script src="@urlEmprende/vendor/datatables/dataTables.bootstrap4.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.5.2/js/dataTables.buttons.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.5.2/js/buttons.bootstrap4.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.36/pdfmake.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.36/vfs_fonts.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.5.2/js/buttons.html5.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.5.2/js/buttons.print.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.5.2/js/buttons.colVis.min.js"></script>

    <script src="~/js/VerPagos.js?v=1.0"></script>
}

<div class="portlet-tittle">
    @*inicio titulo*@
    <ol class="breadcrumb">
        <li class="breadcrumb-item">
            <a href="@Url.Action("Index","Pagos")"><h2> Pagos </h2>  </a>
        </li>
    </ol>
    @*fin titutulo*@


    <div class="row espacioVertical">

        <label class="col-md-2">Desde: </label>
        <input id="txtDesdeTodosPagos" class="col-md-2" type="date" />
        <label class="col-md-2">Hasta: </label>
        <input id="txtHastaTodosPagos" class="col-md-2" type="date" />
        <buttonc id="btnConsultarPagos" class="btn btn-primary  col-md-2 offset-md-1"> Consultar </buttonc>
    </div>

    <div class="card mb-3 espacioVertical">

        <div class="card-header">
            <div class="row">
                <h4 class="col-md-12">Resumen de pagos </h4>
            </div>
        </div>

        <div class="card-body">
            <div class="row">

                <div class="col-sm-12">
                    <table id="tblTodosPagos" class="table table-bordered" width="100%"></table>
                </div>
            </div>
        </div>

        <div class="card-footer">

            <div class="row">
                <label id="txtDescripcion" class="col-md-12">@ViewBag.descripcion</label>
            </div>

        </div>

    </div>



</div>